### ISSUE TITLE
not working on production build

### ISSUE THREAD

**Issue by milon27-pyng** [markjaniczak/symbology-scanner#12]
i am using react js app with vite. the packge works fine on development but after build it doesn't work.

this is my code.

```jsx
import PageWrapper from "@/view/components/layout/page-wrapper"
import { useSymbologyScanner } from "@use-symbology-scanner/react"
import { useState } from "react"

export const DashboardPage = () => {
    const [barcode, setBarcode] = useState<string>("this will be replaced with bar code value.")

    const handleSymbol = (symbol: string) => {
        setBarcode(symbol)
        console.log(`Scanned ${symbol}`)
    }

    useSymbologyScanner(handleSymbol)

    return (
        <PageWrapper hideFooter>
            <div className="text-center py-4">Dashboard</div>
            <p>Barcode: {barcode}</p>
        </PageWrapper>
    )
}


```

**Comment by Jsbarcenas** [comment]
You are right. I am using Nextjs and also is not working when is in production

**Comment by Jsbarcenas** [comment]
Did you find a solution for this ?

**Comment by markjaniczak** [comment]
@milon27-pyng can you tell me more about your environment? Is it SSR like Next.JS or remix, SPA like something with vite or create react app? What actually happens after the build, do you get an error?

**Comment by milon27-pyng** [comment]
it was a React js client side app with Vite.
i am on windows, I have tried deployed in netlify.

after the build it just doesn't work. no error.

**Comment by milon27** [comment]
please share if you could fix the issue. that would be very helpful

**Comment by markjaniczak** [comment]
I'm not able to reproduce the issue you're having in a vite + react environment, see [here](https://codesandbox.io/p/devbox/react-ts-9qputt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm2ckdfvb00073p6m9lwezawg%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm2ckdfvb00023p6m0y9j43rm%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm2ckdfvb00043p6mzfm43sbj%2522%257D%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm2ckdfvb00063p6mzo2zaryz%2522%257D%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm2ckdfvb00023p6m0y9j43rm%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm2ckdfva00013p6moud1eq6w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522cm2ckdfvb00023p6m0y9j43rm%2522%252C%2522activeTabId%2522%253A%2522cm2ckdfva00013p6moud1eq6w%2522%257D%252C%2522cm2ckdfvb00063p6mzo2zaryz%2522%253A%257B%2522id%2522%253A%2522cm2ckdfvb00063p6mzo2zaryz%2522%252C%2522activeTabId%2522%253A%2522cm2ckf3dk002y3p6mvkt5nsmx%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm2ckdfvb00053p6m1yswngfw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A5173%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cm2ckf3dk002y3p6mvkt5nsmx%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522cm2ckdfvb00043p6mzfm43sbj%2522%253A%257B%2522id%2522%253A%2522cm2ckdfvb00043p6mzfm43sbj%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm2ckdfvb00033p6mcm39poro%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cm2ckdfvb00033p6mcm39poro%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D).

Can you provide a codesandbox that reproduces the problem? If you're using a hardware scanner it might be something you need to configure with your scanner.

**Comment by milon27** [comment]
yes its not working with a hardware scanner. how are you testing it?

**Comment by markjaniczak** [comment]
With a Bluetooth Socket scanner. Depending on the model of your scanner, you will likely need to tweak the settings when using the react hook. For example, increasing or decreasing the max time between characters or setting a terminating character like a carriage return.

**Comment by milon27** [comment]
not sure what you are saying. but this npm package is working `react-usb-barcode-scanner` please check this. the problem with this is very old and it has redux dependency

**Comment by markjaniczak** [comment]
That library uses a default delay of 100ms and this one uses 20ms. Have you tried increasing the delay between characters in `scannerOptions`?
