### ISSUE TITLE
Repeating characters

### ISSUE THREAD

**Issue by logan2d** [markjaniczak/symbology-scanner#4]
The ignoreRepeats option doesn't seem to do anything because there are ALOT of repeating characters. Like 6 to 11.

**Comment by markjaniczak** [comment]
I'll need more information to understand what's happening exactly like what hardware you're using. That option only ignores keystrokes when the key is held down on the keyboard. It's possible that your barcode scanner isn't emulating that but instead emulating non-repeating, individual keystrokes.

**Comment by mkromann** [comment]
Hi — thank you for providing this utility :-)

I think I have the same issue as @logan2d.

All characters are repeated. So if I try to scan the barcode `6427015058088` the scanned output is `66442277001155005588008888`.

I am using a Socket Mobile bluetooth scanner. It is in HID mode and works correctly anywhere else (eg. a text input field).

This is my setup in React: `useSymbologyScanner(handleSymbol, { scannerOptions: { maxDelay: 120 } });`. 

What else do you need?

Thank you.

**Comment by mkromann** [comment]
It seems related to the maxDelay setting. If I input a low value, eg. 30 it messes it up entirely:

<img width="324" alt="2024 02 07_14 52 39 • Google Chrome — Mærkbare · Splay Development · Shopify@2x" src="https://github.com/markjaniczak/symbology-scanner/assets/1389467/6a6351dc-dbfe-4d8c-9ff8-bb6cd1ce115f">

And if I input a high value (eg. 150) it looks like this: 

<img width="546" alt="2024 02 07_14 53 50 • Google Chrome — Mærkbare · Splay Development · Shopify@2x" src="https://github.com/markjaniczak/symbology-scanner/assets/1389467/e325ed29-3e94-44d0-a6d8-403ec994a14a">

Both of those screenshots were a single barcode scan. Also it seems to trigger on normal keystrokes every time.

**Comment by javierlimonta** [comment]
> Hi — thank you for providing this utility :-)
> 
> I think I have the same issue as @logan2d.
> 
> All characters are repeated. So if I try to scan the barcode `6427015058088` the scanned output is `66442277001155005588008888`.
> 
> I am using a Socket Mobile bluetooth scanner. It is in HID mode and works correctly anywhere else (eg. a text input field).
> 
> This is my setup in React: `useSymbologyScanner(handleSymbol, { scannerOptions: { maxDelay: 120 } });`.
> 
> What else do you need?
> 
> Thank you.

I have the same issue. Never scan the exact text. Always repeat twice character by character

**Comment by markjaniczak** [comment]
@mkromann thanks for the added info. I'm rewriting tests to see if I can catch this issue. By nature this utility will capture regular keystrokes, particularly as `maxDelay` increases. The best way to resolve that is to configure your scanner to send a suffix character like a line return.

**Comment by markjaniczak** [comment]
This seemed to be an issue with React strict mode reusing state across renders. @mkromann can you update to the latest version and let me know if you have the same issue?

**Comment by javierlimonta** [comment]
Hi there
Yea I use Bluetooth Scanner. Barcode Scanner APK
Thanks you
Regards

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by javierlimonta** [comment]
Hello There
Still don’t work. I install the latest version and I have the same error
Regards

**Comment by javierlimonta** [comment]
Hi. It keeps repeating text as in @logan2d example without the Strict Mode

**Comment by nd-thang** [comment]
Hi @mkromann, i am using your library with newest reactjs and i sometime encounter this issue. There are 2 type of repeating character _when update code at react but not reload tab in browser_ (i saw suffix hot-update.jsx in console): first type, when i using scanner for getting 14-character code for example 123456.. i got the double length symbol: 112233445566.., the second type i met when i type a key on keyboard, with the length of duplicated characters seem be increased by one after each input key, for example: i type 'a' the got 'aa', next type b, got 'bbb', c then got 'cccc',...

**Comment by elliswilcox** [comment]
Has anyone fixed this issue yet? I am encountering the same and was wondering if anyone could advise me on how to fix, if possible, thanks.

**Comment by Quared** [comment]
Same issue.
Any fix yet?

@markjaniczak

**Comment by elliswilcox** [comment]
> Same issue. Any fix yet?
> 
> @markjaniczak

I've made a PR for the fix that worked for me regarding the repeating chars, not sure if it will work for anyone else but hopefully it will.

**Comment by elliswilcox** [comment]
> > Same issue. Any fix yet?
> > @markjaniczak
> 
> I've made a PR for the fix that worked for me regarding the repeating chars, not sure if it will work for anyone else but hopefully it will.

Also note that if you are using HMR and reload the component with the `useSymbologyScanner` hook in, then the callback will fire multiple times and the repeating chars issue may occur again, no clue why.

**Comment by markjaniczak** [comment]
@elliswilcox @Quared I believe I found the issue where the event listener was not being removed in the controller. Can you please try the latest version and test on your end?

**Comment by elliswilcox** [comment]
> @elliswilcox @Quared I believe I found the issue where the event listener was not being removed in the controller. Can you please try the latest version and test on your end?

Working perfectly now - thank you.
