### ISSUE TITLE
The array in the handler never changes + repeating chars issue

### ISSUE THREAD

**Issue by Quared** [markjaniczak/symbology-scanner#8]
Hey there. I can't find a fix for a problem I get.

A little bit of the context - so I have an array of objects with barcode values inside. After scan, I need to remove the scanned object from the array. However, after removing, the items array is updated well outside of the `handler` but inside of it array still has this object.

Here is the simple code for better understanding:

    const [items, setItems] = useState([{code: '450420745984'}])

    console.log(items) -- Here we will have the items = [] on the second scan

    const onComplete = (code: string) => {
      console.log(items) -- Here we will have items = [{code: '450420745984'}] on the second scan

      const fixedCode = code.replace(/(\r\n|\n|\r)/gm, '')

      const foundItem = items.find((item) => item.code === fixedCode)

      if (!foundItem) {
        return undefined
      }

      return setItems((prev) =>
        prev.filter((el) => el.code !== fixedCode)
      )
    }

    useSymbologyScanner(onComplete, {
      scannerOptions: {maxDelay: 50}
    })

And same problem as others have with repeating chars on multiple scans.
Any idea how to solve it?

@markjaniczak

**Comment by markjaniczak** [comment]
Related to #4
